### ISSUE TITLE
User Story: View the therapists

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#1]
**User Type**
Client-X

**Functionality**
View the name, bio, average rating and hourly rate of each therapist.

**Benefit**
Allow a user to familiarise themselves with the staff and decide who  
they may want to treat them.

---
**Acceptance Criteria**
- [x] User can view therapist details regardless of login status
- Therapist details must display:
  - [x] Name
  - [x] Bio
  - [x] Hourly rate
  - [x] Average rating

*Optional Criteria*
- [ ] Display therapies that therapist performs
- [x] Display photo of therapist
