### ISSUE TITLE
User Story: Delete a booking

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#10]
**User Type**
All

**Functionality**
Delete a booking that has already been made

**Benefit**
Allows a user to cancel a booking if necessary

---
**Acceptance Criteria**
- [ ] A logged in user is able to delete their bookings
- [ ] A user is not able to delete bookings that are not theirs
- [ ] A staff member is able to delete all bookings made with them
- [ ] The owner is able to delete all bookings

**Comment by DaveyJH** [comment]
#70 explains why this will not be completed
