### ISSUE TITLE
User Story: View bookings

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#11]
**User Type**
All

**Functionality**
View bookings currently made

**Benefit**
Allows users to see the time and date of their bookings

---
**Acceptance Criteria**
- [ ] A logged in user is able to view their current bookings
- [ ] A user is not able to view bookings that are not theirs
- [ ] A staff member can see all bookings related to them
- [ ] The owner can view all bookings

**Comment by DaveyJH** [comment]
#70 explains why this will not be completed
