### ISSUE TITLE
User Story: View booking data

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#12]
**User Type**
Owner/Business Advisor

**Functionality**
View quantity and type of bookings made, with filtering

**Benefit**
Allows assessment of business productivity and general analysis

---
**Acceptance Criteria**
- [ ] Logged in Owner/Business Advisor is able to view booking data
- [ ] No other users can view booking data
- [ ] Bookings can be filtered by criteria

**Comment by DaveyJH** [comment]
#70 explains why this will not be completed
