### ISSUE TITLE
User Story: Add a therapy

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#15]
**User Type**
Owner

**Functionality**
Add a therapy type to the website

**Benefit**
Allows the owner to add new therapies to the site

---
**Acceptance Criteria**
- [x] A logged in Owner is able to add therapies with details
- [x] No other user is able to add a therapy
- [x] The therapy is added to the database

**Comment by DaveyJH** [comment]
Closed with f2d1b9a
