### ISSUE TITLE
User Story: Edit a therapy

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#16]
**User Type**
Owner

**Functionality**
Edit an existing therapy

**Benefit**
Allows the Owner to modify the details of a therapy

---
**Acceptance Criteria**
- [x] A logged in Owner is able to edit therapy details
- [x] No other user is able to edit therapies
- [x] Relevant therapy details are updated in the database
