### ISSUE TITLE
User Story: Delete a therapy

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#17]
**User Type**
Owner

**Functionality**
Delete a therapy

**Benefit**
Allows the Owner to remove a therapy that is no longer offered

---
**Acceptance Criteria**
- [x] A logged in Owner is able to delete therapies
- [x] No other user is able to delete a therapy
- [x] The deleted therapy is removed from the database
