### ISSUE TITLE
User Story: Add a therapist

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#18]
**User Type**
Owner

**Functionality**
Add a therapist to the website

**Benefit**
Allows the owner to add new therapists to the site

---
**Acceptance Criteria**
- [x] A logged in Owner is able to add therapists with details
- [x] No other user is able to add a therapist
- [x] The new therapist is added to the database

**Comment by DaveyJH** [comment]
closed with #48
