### ISSUE TITLE
User Story: Edit a therapist

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#19]
**User Type**
Owner

**Functionality**
Edit a therapist's details

**Benefit**
Allows the owner to edit therapists and their details

---
**Acceptance Criteria**
- [x] A logged in Owner is able to edit therapists and their details
- [x] No other user is able to edit a therapist
- [x] Relevant therapist details are updated in the database

**Comment by DaveyJH** [comment]
Closed #54
