### ISSUE TITLE
User Story: View therapies

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#2]
**User Type**
Client-C,X

**Functionality**
View the therapies offered at Mindful Massage ad their benefits

**Benefit**
Learn about the therapies offered so a decision on which treatment to
have can be made

---
**Acceptance Criteria**
- [x] View therapies regardless of login status
- Therapy details must display:
  - [x] Therapy name
  - [x] Benefits of the therapy
  - [x] Description of therapy
  - [x] Duration of therapy

*Optional Criteria*
- [x] Display related image of therapy
- [x] ~Display therapists that carry out therapy~
- [x] Display average rating of therapy
- [x] Display body areas that can be treated
- [x] ~Paginate therapies~

**Comment by DaveyJH** [comment]
Main page to view all therapies completed in [sprint 6](https://github.com/users/DaveyJH/projects/1/views/8)

Individual therapy page to allow reviews and further info in [sprint 7](https://github.com/users/DaveyJH/projects/1/views/10)

**Comment by DaveyJH** [comment]
closed with #65
