### ISSUE TITLE
User Story: Delete a therapist

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#20]
**User Type**
Owner

**Functionality**
Delete a therapist from the website

**Benefit**
Allows the owner to delete therapists if they leave the company

---
**Acceptance Criteria**
- [x] A logged in Owner is able to delete therapists
- [x] No other user is able to delete a therapist
- [x] The deleted therapist is removed from the database

**Comment by DaveyJH** [comment]
Close #54
