### ISSUE TITLE
User Story: Write a review

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#4]
**User Type**
Client-A,B,C,X

**Functionality**
Write a therapy review

**Benefit**
Allows a user to leave feedback for Mindful Massage and provides
insight for others

---
**Acceptance Criteria**
- [x] A logged in user can write a review on a therapy
- [x] A non-logged in user cannot write a review
- [x] Reviews that are written on a therapy are linked to the
correct therapy in the database

**Comment by DaveyJH** [comment]
Closed with #65
