### ISSUE TITLE
User Story: Edit a review

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#5]
**User Type**
Client-A,B,C,X

**Functionality**
Edit a review that has already been written by the current user

**Benefit**
Allow a user to correct any mistakes made in their review

---
**Acceptance Criteria**
- [x] A review written by the currently logged in user is editable
- [x] A review written by any other user is not editable
- [x] The review is updated in the database

**Comment by DaveyJH** [comment]
closed with #66
