### ISSUE TITLE
User Story: Delete a review

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#6]
**User Type**
All

**Functionality**
Delete a review

**Benefit**
- Allows a user to delete a review if they decide to
- Allows an admin/staff member to delete reviews

---
**Acceptance Criteria**
- [x] A review written by the currently logged in user can be deleted
- [x] A standard user cannot delete other user's reviews
- [x] A superuser can delete all reviews

**Comment by DaveyJH** [comment]
closed with #67
