### ISSUE TITLE
User Story: View the prices

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#7]
**User Type**
Client-C,X

**Functionality**
View the price of a therapy performed by a particular therapist

**Benefit**
Allows a user to know the cost of services provided by Mindful Massage

---
**Acceptance Criteria**
- [ ] Cost is displayed for chosen therapy/therapist
- [ ] Cost is accurate considering duration and hourly rate
- [ ] Cost is not displayed unless specific details are chosen:
  - Therapist
  - Therapy
  - Body area(s) if applicable as this may affect duration

**Comment by DaveyJH** [comment]
This will not feature in this deployment. As bookings the booking feature will take too long in the time constraints, a simplified page with a contact telephone number will be displayed.

As such, there is no way to select a therapy and therapist simultaneously, thus meaning no prices can be shown. Each therapist has a cost per hour, and each therapy has a duration (which may be variable) so I believe there is enough information for the application (with reduced scope from the initial conception).
