### ISSUE TITLE
User Story: Make a booking

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#8]
**User Type**
All

**Functionality**
Make a booking with a therapist at a specific time, for a specific
therapy

**Benefit**
- Allows Mindful Massage to start taking digital bookings
- Allows a client to make a booking from the website

---
**Acceptance Criteria**
- [ ] Logged in users are able to make a booking
- [ ] Non-logged in users are not able to make a booking
- [ ] Bookings cannot be made if diary slots are not available
- [ ] Confirmation of booking is shown on success

**Comment by DaveyJH** [comment]
#70 explains why this will not be completed
