### ISSUE TITLE
User Story: Edit a booking

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/ci-portfolio-four#9]
**User Type**
All

**Functionality**
Edit a booking that has already been made

**Benefit**
- Allows a user to modify their booking if necessary
- Allows staff to modify bookings if necessary

---
**Acceptance Criteria**
- [ ] A logged in user is able to edit their bookings
- [ ] A user is not able to edit bookings that are not theirs
- [ ] A staff member is able to edit all bookings made with them
- [ ] The owner is able to edit all bookings

**Comment by DaveyJH** [comment]
#70 explains why this will not be completed
